# Generated by Django 3.2 on 2022-03-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_letters', models.IntegerField()),
                ('total_vowels', models.IntegerField()),
                ('total_consonants', models.IntegerField()),
                ('average_word_length', models.IntegerField()),
                ('letter_repetitions', models.TextField()),
            ],
        ),
    ]
