# Generated by Django 3.2 on 2022-03-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220303_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteanalysis',
            name='average_word_length',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
