# Generated by Django 3.2 on 2022-03-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_quoteanalysis_average_word_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteanalysis',
            name='average_word_length',
            field=models.IntegerField(),
        ),
    ]
